global:
  scrape_interval: 2s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: alcoholerometer
   static_configs:
     - targets:
       - app:5001
 - job_name: prometheus_push_gateway
   honor_labels: true
   static_configs:
     - targets:
       - prometheus_push_gateway:9091
rule_files:
  - "/etc/prometheus/alerts.yml"